title: "Domingo Club"
description: "Fermented foods & open-source tools"
introduction: "We make fermented food, open-source tools and explore collaboration with natural processes to promote understanding, transparency, resilience and equity in our global food system. Please be gentle we are in the process of making this website ☺✎✄"
footer: "Domingo Club ☼&nbsp;2021 — ✿&nbsp;[[about]], ⁂&nbsp;[[content]], ✉&nbsp;[[newsletter]], ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/)."
navigation:
  "☼☼☼": "index"
  "About": "about"
  "Newsletter": "newsletter"