title: Domingo Club
description: documentation system
introduction: "Domingo Club ... check our [[news]] and our [[about]] page"
footer: "Domingo Club ☼&nbsp;2021 — ✿&nbsp;[[about]], ⁂&nbsp;[[content]], ✉&nbsp;[[newsletter]], ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/)."
navigation:
  "☼☼☼": "index"
  "News": "news"
  "About": "about"
