title: Domingo Club
description: documentation system
introduction: "Domingo Club ... check our [[news]] and our [[about]] page"
footer: "Domingo Club ☼ 2021 — ✿ [[about]], ⁂ [[content]], ✉ [[newsletter]], ☺ [Instagram](https://www.instagram.com/domingoclub/)."
navigation:
  "☼☼☼": "index"
  "News": "news"
  "About": "about"
