title: "Domingo Club"
description: "Fermented food & open-source tools"
introduction: "We make fermented food, open-source tools and explore collaboration with natural processes to promote understanding, transparency, resilience and equity in our global food system."
footer: "Domingo Club ☼&nbsp;2021 — ✿&nbsp;[About](about-en.html), ⁂&nbsp;[Content](content.html), ✉&nbsp;[[newsletter]], ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/)."
navigation:
  "☼☼☼": "index"
  "About": "about-en"
  "Newsletter": "newsletter"