title: "Domingo Club"
description: "Fermented food & open-source tools"
language: "en"
main_url: "https://domingoclub.com"
introduction: "We promote fermented plant-based protein and build tools so that everyone can make them at home for the benefit of our lives and our planet."
footer: "⁂&nbsp;[Content](content.html), ✉&nbsp;[newsletter](newsletter.html), ▤&nbsp;[RSS feed](https://domingoclub.com/rss.xml), ◌&nbsp;[Mastodon](https://sunbeam.city/@domingoclub/), ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/).<br>Domingo Club ☼&nbsp;2021 — [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
topbar: "
  For worldwide free shipping for orders over 100EUR, use the code FREESHIPPINGWORLD ✿ For free shipping within EU for orders over 75EUR, use the code FREESHIPPINGEU"
navigation:
  "☼☼☼": "index"
  # "Food": "food"
  "Shop": "shop"
  "Journal": "journal"
  "About": "about"
  "Contact": "contact"
analytics:  "
<script>
  var _paq = window._paq = window._paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u='//analytics.antoine.studio/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '2']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>"
