title: "Domingo Club"
description: "Fermented food & open-source tools"
language: "en"
main_url: "https://domingoclub.com"
introduction: "We make fermented food, open-source tools and explore collaboration with natural processes to promote understanding, transparency, resilience and equity in our global food system."
footer: "✿&nbsp;[About](about-en.html), ⁂&nbsp;[Content](content.html), ✉&nbsp;[[newsletter]], ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/).<br>Domingo Club ☼&nbsp;2021 — [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
navigation:
  "☼☼☼": "index"
  "Food": "food"
  "Tools": "tools"
  "About": "about-en"
  "Join" : "join-en"