title: "Domingo Club"
description: "Fermented food & open-source tools"
language: "en"
main_url: "https://domingoclub.com"
introduction: "We make fermented food, open-source tools and explore collaboration with natural processes to promote understanding, transparency, resilience and equity in our global food system."
footer: "⁂&nbsp;[Content](content.html), ✉&nbsp;[newsletter](newsletter.html), ▤&nbsp;[RSS feed](https://domingoclub.com/rss.xml), ◌&nbsp;[Mastodon](https://sunbeam.city/@domingoclub/), ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/).<br>Domingo Club ☼&nbsp;2021 — [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
topbar: "Ferment your own plant-based protein with the heat of your body using the [Domingo Necklace](domingo-necklace.html) ✿"
navigation:
  "☼☼☼": "index"
  # "Food": "food"
  "Shop": "shop"
  "Journal": "journal"
  "About": "about"
analytics:  "
<script>
  var _paq = window._paq = window._paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u='//analytics.antoine.studio/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '2']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>"
