title: "Domingo Club"
description: "Fermented food & open-source tools"
language: "en"
main_url: "https://domingoclub.com"
introduction: "We make fermented food, open-source tools and explore collaboration with natural processes to promote understanding, transparency, resilience and equity in our global food system."
footer: "⁂&nbsp;[Content](content.html), ✉&nbsp;[newsletter](newsletter.html), ▤&nbsp;[RSS feed](https://domingoclub.com/rss.xml), ◌&nbsp;[Mastodon](https://sunbeam.city/@domingoclub/), ※&nbsp;[Github](https://github.com/domingoclub/), ☺&nbsp;[Instagram](https://www.instagram.com/domingoclub/).<br>Domingo Club ☼&nbsp;2021 — [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
navigation:
  "☼☼☼": "index"
  # "Food": "food"
  # "Tools": "tools"
  "Journal": "journal"
  "About": "about"
  "Join the club ✿" : "join"
shop:
  isActive: True
  header: '<link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css" />'
  menu: '<button class="snipcart-checkout"></span> Cart (<span class="snipcart-items-count"></span>)</button>'
  footer: '<script async src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js"></script>
<div id="snipcart" data-config-modal-style="side" data-api-key="YTVkZTgyMmUtOWJjZi00YmYyLWFjNzctOWExZGQ1NWIwNjU5NjM3NjM3NzU3Nzk5MDQxNzM3" hidden></div>'

